---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    #config:
  phpcodesniffer:
    enabled: true
    config:
      standard: "Wordpress"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths:
- tests/*
- bin/*
